FROM tiangolo/uvicorn-gunicorn-fastapi:python3.7
WORKDIR /api

RUN pip install --upgrade pip
RUN pip install --upgrade setuptools
RUN pip install python-dotenv
RUN pip install google-api-python-client
